[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.4.0-rc.7"
edition = "2021"
license = "MIT"
repository = "https://github.com/johnhkchen/lisa"
homepage = "https://github.com/johnhkchen/lisa"
authors = ["John Chen <john.hk.chen@gmail.com>"]

[profile.release]
opt-level = "s"
lto = true

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
