#!/usr/bin/env bash
set -euo pipefail

# Derive the tap's three channel formulae from the one formula cargo-dist writes.
#
# Homebrew already says "which line of this software do you want" with the
# formula name -- python@3.11, postgresql@16 -- so Lisa says it the same way:
#
#   brew install lisa           stable   the newest release that is not a prerelease
#   brew install lisa-nightly   nightly  the release the soak promotion has raised
#   brew install lisa-canary    canary   every release, prerelease or not
#
# cargo-dist emits exactly one formula, so the other two are derived here rather
# than maintained by hand. A formula that drifts because somebody forgot to bump
# it is the failure this exists to prevent.
#
# The rule, and it lives here rather than in the release workflow so a script can
# rehearse it:
#
#   canary   <- this release, every time
#   stable   <- this release, only when it is not a prerelease
#   nightly  <- the release the promotion pointer names, which the caller resolves
#               and hands in; a release publish never chooses it
#
# Nothing is rewritten when the contents would not change, so a tap's history
# stays readable during an incident.
#
# Usage:
#   publish-tap-formulae.sh <tap-checkout> <release-formula.rb> <is-prerelease> <nightly-formula.rb>
#
#   <tap-checkout>       a checkout of johnhkchen/homebrew-lisa (writes Formula/*.rb)
#   <release-formula.rb> the .rb cargo-dist built for the release being published
#   <is-prerelease>      true | false, from dist's announcement_is_prerelease
#   <nightly-formula.rb> the .rb of the release nightly should carry

stable_formula=lisa
nightly_formula=lisa-nightly
canary_formula=lisa-canary

fail() {
    echo "publish-tap-formulae: $*" >&2
    exit 1
}

[[ $# -eq 4 ]] ||
    fail "usage: $(basename "$0") <tap-checkout> <release-formula.rb> <is-prerelease> <nightly-formula.rb>"

tap_checkout=$1
release_source=$2
is_prerelease=$3
nightly_source=$4

[[ -d $tap_checkout ]] || fail "tap checkout does not exist: $tap_checkout"
[[ -s $release_source ]] || fail "missing cargo-dist formula for this release: $release_source"
[[ -s $nightly_source ]] || fail "missing the formula nightly should carry: $nightly_source"
case $is_prerelease in
true | false) ;;
*) fail "is-prerelease must be true or false, got: $is_prerelease" ;;
esac

formula_dir="$tap_checkout/Formula"
mkdir -p "$formula_dir"

formula_version() {
    awk -F'"' '/^  version "/ { print $2; exit }' "$1"
}

# lisa-nightly -> LisaNightly, the class name Homebrew derives from a file name.
formula_class() {
    local name=$1 part rest out=""
    local IFS='-'
    # shellcheck disable=SC2206 # word splitting on '-' is the point.
    local parts=($name)
    for part in "${parts[@]}"; do
        rest=${part#?}
        out="$out$(printf '%s' "${part%"$rest"}" | tr '[:lower:]' '[:upper:]')$rest"
    done
    printf '%s' "$out"
}

# The other two formula names, in tap order, for conflicts_with.
siblings_of() {
    local name=$1 candidate first=1
    for candidate in "$stable_formula" "$nightly_formula" "$canary_formula"; do
        [[ $candidate == "$name" ]] && continue
        if [[ $first -eq 1 ]]; then
            first=0
        else
            printf ', '
        fi
        printf '"%s"' "$candidate"
    done
}

render() {
    local name=$1 channel=$2 source=$3 destination=$4 reason=$5
    local class conflicts version
    class=$(formula_class "$name")
    version=$(formula_version "$source")
    [[ -n $version ]] || fail "no version line in $source"

    # One Lisa and one channel per machine. Without this all three link a bin/lisa
    # and PATH order decides which one runs; with it brew refuses and says why.
    # Homebrew loads the named siblings to check, which is why installing from
    # this tap needs `brew trust johnhkchen/lisa` first.
    conflicts="  conflicts_with $(siblings_of "$name"), because: \"they install lisa from different release channels\""

    awk \
        -v class="$class" \
        -v channel="$channel" \
        -v conflicts="$conflicts" \
        -v generator="scripts/publish-tap-formulae.sh in johnhkchen/lisa" '
        BEGIN {
            print "# Generated by " generator ". Do not edit by hand:"
            print "# the next release regenerates this file and your edit disappears."
            print "# Channel: " channel "."
            renamed = 0
            conflicted = 0
        }
        /^class [A-Za-z0-9_]+ < Formula$/ {
            print "class " class " < Formula"
            renamed = 1
            next
        }
        /^  desc "/ {
            sub(/"[ \t]*$/, " (" channel " channel)\"")
            print
            next
        }
        /^  license "/ {
            print
            print conflicts
            conflicted = 1
            next
        }
        { print }
        END {
            if (renamed != 1) {
                print "publish-tap-formulae: no `class ... < Formula` line to rename" > "/dev/stderr"
                exit 1
            }
            if (conflicted != 1) {
                print "publish-tap-formulae: no `license` line to anchor conflicts_with" > "/dev/stderr"
                exit 1
            }
        }
    ' "$source" >"$destination.tmp" || fail "could not render $name from $source"

    if [[ -e $destination ]] && cmp -s "$destination.tmp" "$destination"; then
        rm -f "$destination.tmp"
        echo "unchanged Formula/$name.rb ($version)"
        return
    fi

    mv "$destination.tmp" "$destination"
    echo "wrote Formula/$name.rb ($version) -- $reason"
}

render "$canary_formula" canary "$release_source" "$formula_dir/$canary_formula.rb" \
    "canary takes every release"

if [[ $is_prerelease == false ]]; then
    render "$stable_formula" stable "$release_source" "$formula_dir/$stable_formula.rb" \
        "stable takes releases that are not prereleases"
else
    echo "skipped Formula/$stable_formula.rb -- $(formula_version "$release_source") is a prerelease and stable never takes one"
fi

render "$nightly_formula" nightly "$nightly_source" "$formula_dir/$nightly_formula.rb" \
    "nightly carries the release the soak promotion points at"
