#!/usr/bin/env bash
set -euo pipefail

# Derive the tap's three channel formulae from the one formula cargo-dist writes.
#
# Homebrew already says "which line of this software do you want" with the
# formula name -- python@3.11, postgresql@16 -- so Lisa says it the same way:
#
#   brew install lisa           stable   the newest release that is not a prerelease
#   brew install lisa-nightly   nightly  a release that has soaked (written by the promotion job)
#   brew install lisa-canary    canary   every release, prerelease or not
#
# cargo-dist emits exactly one formula, so the other two are derived here rather
# than maintained by hand. A formula that drifts because somebody forgot to bump
# it is the failure this exists to prevent.
#
# Usage:
#   publish-tap-formulae.sh <dist-formula.rb> <tap-checkout> <version> <is-prerelease>
#
#   <dist-formula.rb>  the .rb cargo-dist built for this release
#   <tap-checkout>     a checkout of johnhkchen/homebrew-lisa (writes Formula/*.rb)
#   <version>          the release version, e.g. 0.5.0-rc.2 (used in messages only)
#   <is-prerelease>    true | false, from dist's announcement_is_prerelease

tap_owner=johnhkchen
tap_name=lisa
stable_formula=lisa
nightly_formula=lisa-nightly
canary_formula=lisa-canary

fail() {
    echo "publish-tap-formulae: $*" >&2
    exit 1
}

[[ $# -eq 4 ]] || fail "usage: $(basename "$0") <dist-formula.rb> <tap-checkout> <version> <is-prerelease>"

source_formula=$1
tap_checkout=$2
version=$3
is_prerelease=$4

[[ -s $source_formula ]] || fail "missing cargo-dist formula: $source_formula"
[[ -d $tap_checkout ]] || fail "tap checkout does not exist: $tap_checkout"
case $is_prerelease in
true | false) ;;
*) fail "is-prerelease must be true or false, got: $is_prerelease" ;;
esac

formula_dir="$tap_checkout/Formula"
mkdir -p "$formula_dir"

# lisa-nightly -> LisaNightly, the class name Homebrew derives from a file name.
formula_class() {
    local name=$1 part rest out=""
    local IFS='-'
    # shellcheck disable=SC2206 # word splitting on '-' is the point.
    local parts=($name)
    for part in "${parts[@]}"; do
        rest=${part#?}
        out="$out$(printf '%s' "${part%"$rest"}" | tr '[:lower:]' '[:upper:]')$rest"
    done
    printf '%s' "$out"
}

# The other two formula names, in tap order, for conflicts_with.
siblings_of() {
    local name=$1 candidate first=1
    for candidate in "$stable_formula" "$nightly_formula" "$canary_formula"; do
        [[ $candidate == "$name" ]] && continue
        if [[ $first -eq 1 ]]; then
            first=0
        else
            printf ', '
        fi
        printf '"%s"' "$candidate"
    done
}

render() {
    local name=$1 channel=$2 destination=$3
    local class conflicts
    class=$(formula_class "$name")
    # One Lisa and one channel per machine. Without this all three link a bin/lisa
    # and PATH order decides which one runs; with it brew refuses and says why.
    conflicts="  conflicts_with $(siblings_of "$name"), because: \"they install lisa from different release channels\""

    awk \
        -v class="$class" \
        -v channel="$channel" \
        -v conflicts="$conflicts" \
        -v generator="scripts/publish-tap-formulae.sh in johnhkchen/lisa" '
        BEGIN {
            print "# Generated by " generator ". Do not edit by hand:"
            print "# the next release regenerates this file and your edit disappears."
            print "# Channel: " channel "."
            renamed = 0
            conflicted = 0
        }
        /^class [A-Za-z0-9_]+ < Formula$/ {
            print "class " class " < Formula"
            renamed = 1
            next
        }
        /^  desc "/ {
            sub(/"[ \t]*$/, " (" channel " channel)\"")
            print
            next
        }
        /^  license "/ {
            print
            print conflicts
            conflicted = 1
            next
        }
        { print }
        END {
            if (renamed != 1) {
                print "publish-tap-formulae: no `class ... < Formula` line to rename" > "/dev/stderr"
                exit 1
            }
            if (conflicted != 1) {
                print "publish-tap-formulae: no `license` line to anchor conflicts_with" > "/dev/stderr"
                exit 1
            }
        }
    ' "$source_formula" >"$destination.tmp"

    mv "$destination.tmp" "$destination"
}

# The routing. Canary means every release; stable means only a release that is
# not a prerelease; nightly is written by the promotion job (T-069-01-03) and is
# only seeded here so there is a formula for it to promote into.
wrote=0

render "$canary_formula" canary "$formula_dir/$canary_formula.rb"
echo "wrote Formula/$canary_formula.rb ($version) -- canary takes every release"
wrote=$((wrote + 1))

if [[ $is_prerelease == false ]]; then
    render "$stable_formula" stable "$formula_dir/$stable_formula.rb"
    echo "wrote Formula/$stable_formula.rb ($version) -- stable takes non-prerelease releases"
    wrote=$((wrote + 1))
else
    echo "skipped Formula/$stable_formula.rb -- $version is a prerelease and stable never takes one"
fi

if [[ -e $formula_dir/$nightly_formula.rb ]]; then
    echo "skipped Formula/$nightly_formula.rb -- nightly is written by the soak promotion, not by a release"
else
    render "$nightly_formula" nightly "$formula_dir/$nightly_formula.rb"
    echo "wrote Formula/$nightly_formula.rb ($version) -- seeded once so nightly exists to be promoted into"
    wrote=$((wrote + 1))
fi

echo "tap $tap_owner/$tap_name: $wrote formula file(s) generated from $(basename "$source_formula")"
