//! One account of how a project differs from what this binary would create.
//!
//! `lisa doctor` renders it, `lisa init` acts on the part it can prove is safe,
//! and `lisa clean` acts where a person has said to. All three read [`inventory`];
//! none of them re-derives staleness. That is the whole point of the module: if
//! each command computed its own answer, the three would disagree the first time
//! any of them changed, and an operator would be told to run a command that then
//! reports nothing to do.
//!
//! Nothing here prints. The function returns data; the caller decides how much
//! of it a human should see.
//!
//! ## The three categories
//!
//! - **Behind** — a Lisa-owned thing that exists, is byte-recognisable as a Lisa
//!   generation, and has a newer form. This is not judged here: it is whatever
//!   [`crate::init::plan_init_actions`] says it would update, so the diagnosis
//!   and the fix cannot drift apart.
//! - **Retired** — a Lisa-owned thing that exists and has no newer form, because
//!   Lisa stopped producing it: the old workflow document, `scheduling.auto_advance`,
//!   and a `CLAUDE.md`/`AGENTS.md` whose bytes match a generator Lisa no longer
//!   ships (see [`crate::legacy_context`]).
//! - **Stale content in files Lisa does not own** — a ticket whose `phase:` names
//!   a phase retired in 0.5.0. Lisa owns the vocabulary; the board is the
//!   operator's. Reported, never rewritten.
//!
//! ## How a finding gets its remedy
//!
//! Never by hard-coding a command next to a category. A finding's remedy is read
//! back off init's own plan: if init would resolve it, the remedy is `lisa init`,
//! and otherwise removal is the only thing that will, so the remedy is
//! `lisa clean`. Teaching init a new retirement (T-057-02-02) therefore moves the
//! remedy on its own, with no edit here and no window where doctor names a
//! command that does nothing.

use std::path::{Path, PathBuf};

use lisa_core::types::RETIRED_PHASE_NAMES;

use crate::config;
use crate::init::{plan_init_actions, InitAction};
use crate::legacy_context::{
    bears_lisa_agents_marks, bears_lisa_claude_marks, is_generated_agents_md,
    is_generated_claude_md,
};

/// The document Lisa installed while the workflow was called RDSPI.
const RETIRED_WORKFLOW_DOCUMENT: &str = "docs/knowledge/rdspi-workflow.md";
/// Where 0.5.0 installs it instead.
const CURRENT_WORKFLOW_DOCUMENT: &str = "docs/knowledge/lisa-workflow.md";
/// The scheduling key 0.5.0 stopped reading.
const RETIRED_CONFIG_KEY: &str = config::RETIRED_SCHEDULING_KEY;
/// Where tickets live when `.lisa.toml` does not say otherwise.
const DEFAULT_TICKET_DIR: &str = "docs/active/tickets";
/// The two agent-context files Lisa used to generate. `AGENTS.md` comes first
/// deliberately: it is a pointer at `CLAUDE.md`, so `CLAUDE.md`'s own
/// disposition has to be able to read what happens to it.
const AGENTS_CONTEXT_FILE: &str = "AGENTS.md";
const CLAUDE_CONTEXT_FILE: &str = "CLAUDE.md";

/// The reason a proven, unedited generation is removable.
const GENERATED_AND_UNEDITED: &str =
    "generated by Lisa and unedited since; Lisa no longer writes agent-context files";

/// Why a finding is in the inventory.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum CurrencyKind {
    /// Lisa still owns this and ships a newer form of it.
    Behind,
    /// Lisa owned this and ships nothing in its place.
    Retired,
    /// A file Lisa does not own, carrying vocabulary Lisa retired.
    StaleContent,
}

impl CurrencyKind {
    /// A short operator-facing label, aligned for a column of findings.
    pub fn label(self) -> &'static str {
        match self {
            CurrencyKind::Behind => "behind",
            CurrencyKind::Retired => "retired",
            CurrencyKind::StaleContent => "ticket",
        }
    }
}

/// What resolves a finding.
///
/// Every finding carries one. A diagnosis whose remedy the reader has to infer
/// is worse than no diagnosis at all, so there is no "none" here — where no
/// command applies, [`Remedy::Operator`] states the edit in words.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Remedy {
    /// `lisa init` carries this forward.
    Init,
    /// Nothing carries it forward; removal is the fix, under explicit consent.
    Clean,
    /// The file is the operator's. The string names the exact edit.
    Operator(String),
}

impl Remedy {
    /// The one line a reader acts on.
    pub fn line(&self) -> String {
        match self {
            Remedy::Init => "run `lisa init`".to_string(),
            Remedy::Clean => "run `lisa clean`".to_string(),
            Remedy::Operator(edit) => edit.clone(),
        }
    }
}

/// One way this project differs from what the running binary would create.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CurrencyFinding {
    pub kind: CurrencyKind,
    /// What the finding is about — a repository-relative path, or a config key.
    pub subject: String,
    /// One sentence saying what is stale about it.
    pub detail: String,
    pub remedy: Remedy,
}

/// What `.lisa.toml` records about the Lisa that set this project up.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RecordedVersion {
    /// No `.lisa.toml`: not a Lisa project, so there is nothing to be current with.
    NoProject,
    /// `.lisa.toml` exists but could not be read or parsed.
    Unreadable,
    /// Initialised before Lisa recorded a version. Not an error — just old.
    PreVersioning,
    /// Recorded, and older than this binary.
    Behind { recorded: String },
    /// Recorded, and this binary's own version.
    Current { recorded: String },
}

/// A structured account of how this project differs from a fresh `lisa init`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectCurrency {
    pub recorded_version: RecordedVersion,
    /// Every finding, ordered behind → retired → stale content, then by subject.
    pub findings: Vec<CurrencyFinding>,
    /// This binary's version, so a renderer never has to look it up.
    pub current_version: &'static str,
}

impl ProjectCurrency {
    /// True when nothing about this project is behind the running binary.
    pub fn is_current(&self) -> bool {
        self.findings.is_empty()
    }
}

/// One thing at a project root that Lisa used to write and no longer does.
///
/// The shared detection every retirement-aware command reads. `lisa init` maps
/// each [`Disposition`] to a line in its plan; [`inventory`] renders the same
/// list for `lisa doctor`. Neither re-derives it, which is what stops the two
/// from disagreeing the first time either changes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Retirement {
    pub kind: RetirementKind,
    /// What the retirement is about, as an operator would type it: a
    /// repository-relative path, or `.lisa.toml [scheduling] auto_advance`.
    pub subject: String,
    pub disposition: Disposition,
}

/// Which retirement this is. The variants carry only what a *caller* needs to
/// decide how to speak about it; the detail sentences themselves belong to the
/// caller, because init's preview and doctor's report address different readers.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum RetirementKind {
    /// `docs/knowledge/rdspi-workflow.md`, a path Lisa created.
    WorkflowDocument,
    /// `CLAUDE.md` or `AGENTS.md`, paths that belong to the project.
    ///
    /// `proven_generation` is the strong signal: the bytes match a generator
    /// Lisa shipped. When it is false only the weak mark matched — the file is
    /// recognisably a Lisa generation somebody edited, which is enough to say
    /// *preserved* about and never enough to remove or to route to a command
    /// that removes.
    ContextFile { proven_generation: bool },
    /// `[scheduling] auto_advance` in `.lisa.toml`.
    ConfigKey,
    /// A ticket whose `phase:` names a phase retired in 0.5.0.
    TicketPhase { phase: String },
}

/// What may be done about a retirement, decided from bytes alone.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum Disposition {
    /// The bytes prove Lisa wrote this file and nobody has touched it since.
    /// Init may delete it.
    RemoveFile { path: PathBuf, reason: String },
    /// `.lisa.toml` sets a key Lisa no longer reads, and the line lifts out
    /// without disturbing a byte around it.
    DropConfigKey {
        path: PathBuf,
        section: &'static str,
        key: &'static str,
        reason: String,
    },
    /// Leave this exactly as it is. The reason is already worded for a preview
    /// line, `preserved:` prefix and all.
    Preserve { path: PathBuf, reason: String },
}

impl Disposition {
    /// The path this disposition is about.
    pub fn path(&self) -> &Path {
        match self {
            Disposition::RemoveFile { path, .. }
            | Disposition::DropConfigKey { path, .. }
            | Disposition::Preserve { path, .. } => path,
        }
    }
}

/// Everything at `root` that Lisa used to write and no longer does.
///
/// Pure detection: reads the filesystem, changes nothing, prints nothing, and —
/// the constraint the whole module hangs on — **calls nothing in
/// [`crate::init`]**. [`inventory`] reads init's plan to decide each remedy, so
/// a detector that consulted the plan would recurse forever. Init consumes
/// detection; the inventory consumes detection *and* the plan.
pub(crate) fn retirements(root: &Path) -> Vec<Retirement> {
    let mut found = Vec::new();
    found.extend(retired_workflow_document(root));
    found.extend(retired_context_files(root));
    found.extend(retired_config_key(root));
    found.extend(retired_ticket_phases(root));
    found
}

/// The workflow document under the name it carried through 0.4.
///
/// The path is one Lisa created, so anything there is reported. What the bytes
/// decide is whether init may remove it or must leave it: only a generation
/// Lisa shipped is Lisa's to delete.
fn retired_workflow_document(root: &Path) -> Option<Retirement> {
    let path = root.join(RETIRED_WORKFLOW_DOCUMENT);
    if !path.exists() {
        return None;
    }

    let disposition = match std::fs::read_to_string(&path) {
        Ok(existing) if crate::templates::LEGACY_WORKFLOWS.contains(&existing.as_str()) => {
            Disposition::RemoveFile {
                path,
                reason: format!("superseded by {CURRENT_WORKFLOW_DOCUMENT}"),
            }
        }
        Ok(_) => Disposition::Preserve {
            path,
            reason: format!(
                "preserved: content is not a known Lisa template; superseded by {CURRENT_WORKFLOW_DOCUMENT}"
            ),
        },
        Err(_) => Disposition::Preserve {
            path,
            reason: format!(
                "preserved: existing file is unreadable; superseded by {CURRENT_WORKFLOW_DOCUMENT}"
            ),
        },
    };

    Some(Retirement {
        kind: RetirementKind::WorkflowDocument,
        subject: RETIRED_WORKFLOW_DOCUMENT.to_string(),
        disposition,
    })
}

/// `CLAUDE.md` and `AGENTS.md` — the sharp case in the whole ticket.
///
/// These paths belong to the project, not to Lisa, so silence is the default.
/// A byte-match against a generation Lisa shipped proves Lisa wrote the file
/// and the operator never touched it; that one Lisa may retire. A file that
/// still bears a Lisa mark but no longer matches has been edited, and an edit
/// makes it theirs — reported so the operator knows Lisa looked and declined,
/// removable by nothing. Anything else produces no retirement at all.
///
/// `AGENTS.md` is decided first because it is a *pointer at* `CLAUDE.md`.
/// Retiring the pointer while keeping the target is harmless; retiring the
/// target while something still points at it leaves a dangling reference. So
/// the rule is one-directional: **a pointer target is retired only when nothing
/// is left pointing at it.** File order decides nothing.
fn retired_context_files(root: &Path) -> Vec<Retirement> {
    let mut found = Vec::new();

    let agents_path = root.join(AGENTS_CONTEXT_FILE);
    let agents_content = std::fs::read_to_string(&agents_path).ok();
    let agents_is_generated = agents_content
        .as_deref()
        .is_some_and(is_generated_agents_md);

    if let Some(content) = agents_content.as_deref() {
        if agents_is_generated {
            found.push(Retirement {
                kind: RetirementKind::ContextFile {
                    proven_generation: true,
                },
                subject: AGENTS_CONTEXT_FILE.to_string(),
                disposition: Disposition::RemoveFile {
                    path: agents_path,
                    reason: GENERATED_AND_UNEDITED.to_string(),
                },
            });
        } else if bears_lisa_agents_marks(content) {
            found.push(Retirement {
                kind: RetirementKind::ContextFile {
                    proven_generation: false,
                },
                subject: AGENTS_CONTEXT_FILE.to_string(),
                disposition: Disposition::Preserve {
                    path: agents_path,
                    reason: "preserved: edited since Lisa generated it, so it is yours now"
                        .to_string(),
                },
            });
        }
    }

    let claude_path = root.join(CLAUDE_CONTEXT_FILE);
    let Ok(claude_content) = std::fs::read_to_string(&claude_path) else {
        return found;
    };

    if is_generated_claude_md(&claude_content) {
        // Anything remaining at AGENTS.md that names CLAUDE.md would be left
        // pointing at nothing — including an AGENTS.md the operator wrote
        // themselves, which dangles exactly as badly as a generated one.
        let pointer_survives = !agents_is_generated
            && agents_content
                .as_deref()
                .is_some_and(|agents| agents.contains(CLAUDE_CONTEXT_FILE));

        found.push(Retirement {
            kind: RetirementKind::ContextFile {
                proven_generation: true,
            },
            subject: CLAUDE_CONTEXT_FILE.to_string(),
            disposition: if pointer_survives {
                Disposition::Preserve {
                    path: claude_path,
                    reason: format!("preserved: {AGENTS_CONTEXT_FILE} still points at it"),
                }
            } else {
                Disposition::RemoveFile {
                    path: claude_path,
                    reason: GENERATED_AND_UNEDITED.to_string(),
                }
            },
        });
    } else if bears_lisa_claude_marks(&claude_content) {
        found.push(Retirement {
            kind: RetirementKind::ContextFile {
                proven_generation: false,
            },
            subject: CLAUDE_CONTEXT_FILE.to_string(),
            disposition: Disposition::Preserve {
                path: claude_path,
                reason: "preserved: edited since Lisa generated it, so it is yours now".to_string(),
            },
        });
    }

    found
}

/// `scheduling.auto_advance`, which 0.5.0 parses and ignores.
///
/// Whether it is removable is not a judgment made here: [`config::remove_retired_scheduling_key`]
/// tries the edit and reports whether it could be done without reformatting the
/// operator's file. A file that cannot be edited surgically is preserved and
/// said so, which the ticket ranks above a stripped-comment rewrite.
fn retired_config_key(root: &Path) -> Option<Retirement> {
    let path = root.join(".lisa.toml");
    let existing = std::fs::read_to_string(&path).ok()?;

    let disposition = match config::remove_retired_scheduling_key(&existing) {
        config::RetiredKeyRemoval::Absent => return None,
        config::RetiredKeyRemoval::Removed(_) => Disposition::DropConfigKey {
            path,
            section: config::RETIRED_SCHEDULING_SECTION,
            key: RETIRED_CONFIG_KEY,
            reason: "Lisa stopped reading this setting in 0.5.0".to_string(),
        },
        config::RetiredKeyRemoval::NotSurgical(why) => Disposition::Preserve {
            path,
            reason: format!(
                "preserved: [{}] {RETIRED_CONFIG_KEY} is inert since 0.5.0, but {why}",
                config::RETIRED_SCHEDULING_SECTION
            ),
        },
    };

    Some(Retirement {
        kind: RetirementKind::ConfigKey,
        subject: format!(
            ".lisa.toml [{}] {RETIRED_CONFIG_KEY}",
            config::RETIRED_SCHEDULING_SECTION
        ),
        disposition,
    })
}

/// Tickets whose `phase:` names one of the phases retired in 0.5.0.
///
/// Never removable and never rewritable. `docs/active/tickets/` is the
/// operator's board, not a Lisa-owned template, and a retired value still
/// loads: it reads as `implement`, and Lisa rewrites the row itself the next
/// time it moves the ticket. Init reporting them is the whole of init's
/// business here.
///
/// Sorted, so a preview that shows only the first few shows the same few every
/// run rather than whatever order the directory happened to be read in.
fn retired_ticket_phases(root: &Path) -> Vec<Retirement> {
    let ticket_dir = root.join(configured_ticket_dir(root));
    let Ok(entries) = std::fs::read_dir(&ticket_dir) else {
        return Vec::new();
    };

    let mut found = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().is_none_or(|ext| ext != "md") {
            continue;
        }
        let Ok(content) = std::fs::read_to_string(&path) else {
            continue;
        };
        let Some(phase) = frontmatter_value(&content, "phase") else {
            continue;
        };
        if !RETIRED_PHASE_NAMES.contains(&phase.as_str()) {
            continue;
        }
        found.push(Retirement {
            kind: RetirementKind::TicketPhase {
                phase: phase.clone(),
            },
            subject: relative(root, &path),
            disposition: Disposition::Preserve {
                path,
                reason: format!(
                    "preserved: records `phase: {phase}`, retired in 0.5.0; your board is not \
                     Lisa's to rewrite"
                ),
            },
        });
    }
    found.sort_by(|left, right| left.subject.cmp(&right.subject));
    found
}

/// Take an account of how the project at `root` differs from what this binary
/// would create. Reads the filesystem; changes nothing; prints nothing.
pub fn inventory(root: &Path) -> ProjectCurrency {
    let current_version = config::LISA_VERSION;
    let config_path = root.join(".lisa.toml");

    if !config_path.exists() {
        return ProjectCurrency {
            recorded_version: RecordedVersion::NoProject,
            findings: Vec::new(),
            current_version,
        };
    }

    let config_text = std::fs::read_to_string(&config_path).ok();
    let config_table = config_text
        .as_deref()
        .and_then(|text| text.parse::<toml::Value>().ok());

    let recorded_version = match (&config_text, &config_table) {
        (None, _) | (_, None) => RecordedVersion::Unreadable,
        (Some(text), Some(_)) => match toml::from_str::<config::LisaConfig>(text)
            .ok()
            .and_then(|parsed| parsed.version)
        {
            None => RecordedVersion::PreVersioning,
            Some(recorded) if config::version_is_stale(&recorded, current_version) => {
                RecordedVersion::Behind { recorded }
            }
            Some(recorded) => RecordedVersion::Current { recorded },
        },
    };

    let plan = plan_init_actions(root);
    let mut findings = Vec::new();

    let version_finding = version_finding(&recorded_version, current_version);
    let config_already_reported = version_finding.is_some();
    findings.extend(version_finding);
    findings.extend(behind_findings(root, &plan, config_already_reported));
    findings.extend(retirement_findings(&retirements(root), &plan));

    findings.sort_by(|left, right| {
        left.kind
            .cmp(&right.kind)
            .then_with(|| left.subject.cmp(&right.subject))
    });

    ProjectCurrency {
        recorded_version,
        findings,
        current_version,
    }
}

/// What the recorded version says, as a finding a reader can act on.
///
/// An absent `version` key is "initialised before Lisa recorded one", not a
/// fault: Lisa did not always write it, and a project that predates the key is
/// simply old.
fn version_finding(
    recorded_version: &RecordedVersion,
    current_version: &str,
) -> Option<CurrencyFinding> {
    let detail = match recorded_version {
        RecordedVersion::Behind { recorded } => {
            format!("Set up by Lisa {recorded}; this Lisa is {current_version}.")
        }
        RecordedVersion::PreVersioning => format!(
            "Set up before Lisa recorded a version, so it predates {current_version} by an unknown distance."
        ),
        RecordedVersion::Current { .. }
        | RecordedVersion::Unreadable
        | RecordedVersion::NoProject => return None,
    };

    Some(CurrencyFinding {
        kind: CurrencyKind::Behind,
        subject: ".lisa.toml".to_string(),
        detail,
        remedy: Remedy::Init,
    })
}

/// Everything init would refresh in place, taken straight from its plan.
///
/// `.lisa.toml` is handled apart from the rest. Its recorded version is already
/// a finding of its own, and one upgrade reported twice against the same file
/// reads as two problems — so the settings line is emitted only when the
/// version had nothing to say, which is the case a current version hides: keys
/// Lisa added since are upserted without a version bump.
fn behind_findings(
    root: &Path,
    plan: &[InitAction],
    config_already_reported: bool,
) -> Vec<CurrencyFinding> {
    let mut findings = Vec::new();
    for action in plan {
        let InitAction::UpdateFile { path, .. } = action else {
            continue;
        };
        let subject = relative(root, path);
        if subject == ".lisa.toml" {
            if !config_already_reported {
                findings.push(CurrencyFinding {
                    kind: CurrencyKind::Behind,
                    subject,
                    detail: "Settings Lisa added since this file was written are missing from it."
                        .to_string(),
                    remedy: Remedy::Init,
                });
            }
            continue;
        }
        findings.push(CurrencyFinding {
            kind: CurrencyKind::Behind,
            subject,
            detail: "An older Lisa generation is installed here; a newer one exists.".to_string(),
            remedy: Remedy::Init,
        });
    }
    findings
}

/// Every retirement, rendered for the reader `lisa doctor` writes to.
///
/// The remedy is never hard-coded next to a category: it is read back off
/// init's own plan, so teaching init a new retirement moves the remedy on its
/// own and there is no window where doctor names a command that does nothing.
/// The `Disposition` could answer the same question directly — but the plan is
/// what will actually run, and that is what makes doctor's promise true.
fn retirement_findings(retired: &[Retirement], plan: &[InitAction]) -> Vec<CurrencyFinding> {
    retired
        .iter()
        .filter_map(|retirement| {
            let resolved_by_init = plan_resolves(plan, &retirement.disposition);
            let carried_forward = |detail: String| CurrencyFinding {
                kind: CurrencyKind::Retired,
                subject: retirement.subject.clone(),
                detail,
                remedy: if resolved_by_init {
                    Remedy::Init
                } else {
                    Remedy::Clean
                },
            };

            match &retirement.kind {
                RetirementKind::WorkflowDocument => Some(carried_forward(if resolved_by_init {
                    format!("Describes a workflow Lisa no longer runs; {CURRENT_WORKFLOW_DOCUMENT} replaced it.")
                } else {
                    format!(
                        "Describes a workflow Lisa no longer runs, and has been edited since Lisa wrote it, so init leaves it alone. {CURRENT_WORKFLOW_DOCUMENT} replaced it."
                    )
                })),

                // An edited generation stops at init's preview and goes no
                // further. Doctor's every finding names a command, and the
                // command for a retired-and-preserved file is `lisa clean` —
                // one that deletes. The weak mark is evidence enough to say
                // "left alone" beside the file it is about; it is not evidence
                // enough to route somebody's own writing toward a deletion.
                RetirementKind::ContextFile { proven_generation: false } => None,

                RetirementKind::ContextFile { proven_generation: true } => {
                    Some(carried_forward(format!(
                        "Lisa generated this file and stopped maintaining it; the bytes are still \
                         exactly as Lisa wrote them, so nothing of yours is in it. What agents read \
                         now is {CURRENT_WORKFLOW_DOCUMENT}."
                    )))
                }

                // `lisa clean` removes files; it never rewrites the contents of
                // one. When the key lifts out surgically, init has already done
                // it and the remedy is init. When it does not, Lisa has already
                // concluded it cannot edit this file without reformatting bytes
                // the operator wrote — so the remedy is their one-line edit, not
                // a deleting command taking a second opinion on the same file.
                RetirementKind::ConfigKey if !resolved_by_init => Some(CurrencyFinding {
                    kind: CurrencyKind::Retired,
                    subject: retirement.subject.clone(),
                    detail: "Lisa stopped reading this setting in 0.5.0. It is inert, not harmful \
                             — the board advances on its artifacts either way — and init could not \
                             lift the line out without reformatting the rest of your file."
                        .to_string(),
                    remedy: Remedy::Operator(format!(
                        "no Lisa command rewrites your settings. Delete the `{RETIRED_CONFIG_KEY}` \
                         line from [{}] in .lisa.toml yourself; nothing reads it",
                        config::RETIRED_SCHEDULING_SECTION
                    )),
                }),

                RetirementKind::ConfigKey => Some(carried_forward(
                    "Lisa stopped reading this setting in 0.5.0. It is inert, not harmful — the \
                     board advances on its artifacts either way."
                        .to_string(),
                )),

                RetirementKind::TicketPhase { phase } => Some(CurrencyFinding {
                    kind: CurrencyKind::StaleContent,
                    subject: retirement.subject.clone(),
                    detail: format!("Records `phase: {phase}`, a phase Lisa retired in 0.5.0."),
                    remedy: Remedy::Operator(format!(
                        "no Lisa command touches your board. Lisa already reads `{phase}` as \
                         `implement` and rewrites the row itself the next time it moves this ticket; \
                         set `phase: implement` to settle it now"
                    )),
                }),
            }
        })
        .collect()
}

/// Does init's plan actually carry this disposition out?
fn plan_resolves(plan: &[InitAction], disposition: &Disposition) -> bool {
    plan.iter().any(|action| match (action, disposition) {
        (InitAction::RemoveFile { path: planned, .. }, Disposition::RemoveFile { path, .. }) => {
            planned == path
        }
        (
            InitAction::RetireConfigKey { path: planned, .. },
            Disposition::DropConfigKey { path, .. },
        ) => planned == path,
        _ => false,
    })
}

/// Where this project keeps its tickets, falling back to the default when
/// `.lisa.toml` cannot answer.
fn configured_ticket_dir(root: &Path) -> String {
    config::load_config(root)
        .ok()
        .and_then(|validation| validation.config.dirs.tickets)
        .unwrap_or_else(|| DEFAULT_TICKET_DIR.to_string())
}

/// Read one scalar value out of a markdown file's YAML frontmatter block.
///
/// Deliberately raw: [`lisa_core::types::Phase`] maps every retired name
/// forward to `implement`, so a parsed ticket can no longer say which word is
/// actually written in the file.
fn frontmatter_value(content: &str, key: &str) -> Option<String> {
    let mut lines = content.lines();
    if lines.next()?.trim() != "---" {
        return None;
    }
    for line in lines {
        if line.trim() == "---" {
            return None;
        }
        let Some((name, value)) = line.split_once(':') else {
            continue;
        };
        if name.trim() == key {
            return Some(value.trim().trim_matches(['"', '\'']).to_string());
        }
    }
    None
}

/// Render a path the way an operator would type it: relative to the project.
fn relative(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    /// A project shaped like one 0.4.4 left behind: an old recorded version, the
    /// workflow document under its old name, a generated context file, the dead
    /// scheduling key, and a ticket at a retired phase.
    fn fixture_0_4_4(root: &Path) {
        fs::create_dir_all(root.join("docs/knowledge")).unwrap();
        fs::create_dir_all(root.join("docs/active/tickets")).unwrap();
        fs::create_dir_all(root.join(".lisa/hooks")).unwrap();
        // An older recorded version than any binary that can run this test. The
        // fixture is 0.4.4-*shaped*; pinning the string to 0.4.4 would make the
        // version assertion evaporate on exactly the release that ships it.
        fs::write(
            root.join(".lisa.toml"),
            "version = \"0.4.0\"\n\n[scheduling]\nmax_threads = 2\nauto_advance = true\n",
        )
        .unwrap();
        fs::write(
            root.join(RETIRED_WORKFLOW_DOCUMENT),
            crate::templates::LEGACY_WORKFLOWS[2],
        )
        .unwrap();
        fs::write(
            root.join(".lisa/hooks/on-stop.sh"),
            crate::templates::LEGACY_ON_STOP_HOOKS[0],
        )
        .unwrap();
        fs::write(
            root.join("docs/active/tickets/T-024-01.md"),
            "---\nid: T-024-01\nstory: S-024\ntitle: migrate-climate-calls\ntype: task\nstatus: open\npriority: high\nphase: structure\ndepends_on: []\n---\n\n## Context\n\nWork.\n",
        )
        .unwrap();
    }

    fn generated_claude_md() -> String {
        format!(
            "{}my-app (Rust) — TODO: add a one-line project description here.\n\n### Build and Test\n\n```bash\n# Build\ncargo build\n\n# Run tests\ncargo test\n\n# Lint\ncargo clippy\n```\n\n### Source Layout\n\n```\nsrc:\n  main.rs\n```\n\n{}",
            include_str!("../data/legacy/claude-md-header-v0.4.4.md"),
            include_str!("../data/legacy/claude-md-tail.md"),
        )
    }

    fn find<'a>(currency: &'a ProjectCurrency, subject: &str) -> Option<&'a CurrencyFinding> {
        currency
            .findings
            .iter()
            .find(|finding| finding.subject == subject)
    }

    #[test]
    fn a_0_4_4_project_reports_one_of_each_category() {
        let dir = tempfile::tempdir().unwrap();
        fixture_0_4_4(dir.path());

        let currency = inventory(dir.path());

        assert_eq!(
            currency.recorded_version,
            RecordedVersion::Behind {
                recorded: "0.4.0".to_string()
            }
        );
        assert!(!currency.is_current());

        // Behind: a hook script whose bytes are a shipped prior generation.
        let behind = find(&currency, ".lisa/hooks/on-stop.sh")
            .expect("a prior hook generation is behind, not retired");
        assert_eq!(behind.kind, CurrencyKind::Behind);
        assert_eq!(behind.remedy, Remedy::Init);

        // Retired: the workflow document under the name Lisa stopped using.
        let retired =
            find(&currency, RETIRED_WORKFLOW_DOCUMENT).expect("retired workflow document");
        assert_eq!(retired.kind, CurrencyKind::Retired);
        assert_eq!(retired.remedy, Remedy::Init, "init already removes it");
        assert!(retired.detail.contains(CURRENT_WORKFLOW_DOCUMENT));

        // Stale content inside a file Lisa does not own.
        let stale =
            find(&currency, "docs/active/tickets/T-024-01.md").expect("ticket at a retired phase");
        assert_eq!(stale.kind, CurrencyKind::StaleContent);
        assert!(stale.detail.contains("structure"));
        assert!(matches!(stale.remedy, Remedy::Operator(_)));

        // And the dead scheduling key.
        let key = currency
            .findings
            .iter()
            .find(|finding| finding.subject.contains(RETIRED_CONFIG_KEY))
            .expect("retired scheduling key");
        assert_eq!(key.kind, CurrencyKind::Retired);
    }

    #[test]
    fn every_finding_names_a_remedy() {
        let dir = tempfile::tempdir().unwrap();
        fixture_0_4_4(dir.path());
        fs::write(dir.path().join("CLAUDE.md"), generated_claude_md()).unwrap();

        let currency = inventory(dir.path());
        assert!(!currency.findings.is_empty());
        for finding in &currency.findings {
            let line = finding.remedy.line();
            assert!(
                !line.trim().is_empty(),
                "{} has an empty remedy",
                finding.subject
            );
            assert!(
                !finding.detail.trim().is_empty(),
                "{} has an empty detail",
                finding.subject
            );
        }
    }

    #[test]
    fn a_generated_context_file_is_retired_and_a_hand_written_one_is_invisible() {
        let dir = tempfile::tempdir().unwrap();
        fixture_0_4_4(dir.path());

        // Byte-identical to a 0.4.x `generate_claude_md` output.
        fs::write(dir.path().join("CLAUDE.md"), generated_claude_md()).unwrap();
        fs::write(
            dir.path().join("AGENTS.md"),
            crate::legacy_context::LEGACY_AGENTS_CONTEXTS[1],
        )
        .unwrap();

        let currency = inventory(dir.path());
        let claude = find(&currency, "CLAUDE.md").expect("a generated CLAUDE.md is Lisa's litter");
        assert_eq!(claude.kind, CurrencyKind::Retired);
        assert_eq!(
            claude.remedy,
            Remedy::Init,
            "init retires a proven, unedited generation, so init is the fix"
        );
        assert_eq!(
            find(&currency, "AGENTS.md").map(|finding| finding.kind),
            Some(CurrencyKind::Retired)
        );
        assert_eq!(
            find(&currency, "AGENTS.md").map(|finding| finding.remedy.clone()),
            Some(Remedy::Init)
        );

        // The operator's own writing at the same paths.
        fs::write(
            dir.path().join("CLAUDE.md"),
            "# CLAUDE.md\n\nRun the climate suite before every commit.\n",
        )
        .unwrap();
        fs::write(
            dir.path().join("AGENTS.md"),
            "# AGENTS.md\n\nStart with the README.\n",
        )
        .unwrap();

        let currency = inventory(dir.path());
        assert!(
            find(&currency, "CLAUDE.md").is_none(),
            "a hand-written CLAUDE.md is the operator's and is not reported at all"
        );
        assert!(find(&currency, "AGENTS.md").is_none());
    }

    #[test]
    fn an_edited_context_file_is_reported_to_init_and_never_to_doctor() {
        let dir = tempfile::tempdir().unwrap();
        fixture_0_4_4(dir.path());

        // A generated file with one line of Lisa's own prose replaced. It still
        // bears Lisa's preamble, so init has something to say `preserved` about.
        let edited = generated_claude_md().replace(
            "TODO: add a one-line project description here.",
            "A scheduler for climate model runs.",
        );
        fs::write(dir.path().join("CLAUDE.md"), &edited).unwrap();

        // Init names it, so the operator hears that Lisa looked and declined.
        let plan = crate::init::plan_init_actions(dir.path());
        let preserved = plan
            .iter()
            .filter(|action| {
                matches!(action, crate::init::InitAction::SafetySkip { path, .. }
                    if path == &dir.path().join("CLAUDE.md"))
            })
            .count();
        assert_eq!(preserved, 1, "init reports what it preserved: {plan:?}");

        // Doctor does not, and that is the point. Every doctor finding names a
        // command, and the command for a retired-and-preserved file removes it.
        // A prefix match is evidence enough to say "left alone" beside the file
        // it is about; it is not evidence enough to route somebody's own
        // writing toward `lisa clean`.
        assert!(find(&inventory(dir.path()), "CLAUDE.md").is_none());

        // And the file is untouched by the run itself.
        crate::init::run_init(dir.path(), false, crate::init::HistoryPreference::NoHistory)
            .unwrap();
        assert_eq!(
            fs::read_to_string(dir.path().join("CLAUDE.md")).unwrap(),
            edited
        );
    }

    #[test]
    fn a_pointer_left_at_agents_md_keeps_claude_md() {
        let dir = tempfile::tempdir().unwrap();
        fixture_0_4_4(dir.path());
        fs::write(dir.path().join("CLAUDE.md"), generated_claude_md()).unwrap();
        // The operator's own AGENTS.md, naming CLAUDE.md. Removing CLAUDE.md
        // would leave it pointing at nothing.
        fs::write(
            dir.path().join("AGENTS.md"),
            "# AGENTS.md\n\nRead CLAUDE.md first, then the README.\n",
        )
        .unwrap();

        let currency = inventory(dir.path());
        let claude = find(&currency, "CLAUDE.md").expect("still Lisa's litter, still reported");
        assert_eq!(
            claude.remedy,
            Remedy::Clean,
            "init will not remove a pointer target while something points at it"
        );
        assert!(
            find(&currency, "AGENTS.md").is_none(),
            "a hand-written AGENTS.md is the operator's and is not reported at all"
        );
    }

    #[test]
    fn a_missing_version_key_is_pre_versioning_not_an_error() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(
            dir.path().join(".lisa.toml"),
            "[scheduling]\nmax_threads = 2\n",
        )
        .unwrap();

        let currency = inventory(dir.path());
        assert_eq!(currency.recorded_version, RecordedVersion::PreVersioning);
        let finding = find(&currency, ".lisa.toml").expect("pre-versioning is reported");
        assert_eq!(finding.kind, CurrencyKind::Behind);
        assert_eq!(finding.remedy, Remedy::Init);
        assert!(finding.detail.contains("before Lisa recorded a version"));
    }

    #[test]
    fn an_edited_retired_document_needs_removal_rather_than_init() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join("docs/knowledge")).unwrap();
        fs::write(
            dir.path().join(".lisa.toml"),
            format!("version = \"{}\"\n", config::LISA_VERSION),
        )
        .unwrap();
        fs::write(
            dir.path().join(RETIRED_WORKFLOW_DOCUMENT),
            format!(
                "{}\n\nOur team's note.\n",
                crate::templates::LEGACY_WORKFLOWS[2]
            ),
        )
        .unwrap();

        let currency = inventory(dir.path());
        let finding = find(&currency, RETIRED_WORKFLOW_DOCUMENT).expect("still reported");
        assert_eq!(finding.kind, CurrencyKind::Retired);
        assert_eq!(finding.remedy, Remedy::Clean);
    }

    #[test]
    fn a_fresh_init_project_is_current() {
        let dir = tempfile::tempdir().unwrap();
        crate::init::run_init(dir.path(), false, crate::init::HistoryPreference::NoHistory)
            .expect("init must succeed in an empty directory");

        let currency = inventory(dir.path());
        assert_eq!(
            currency.findings,
            Vec::new(),
            "what init just wrote cannot already be stale"
        );
        assert!(currency.is_current());
        assert_eq!(
            currency.recorded_version,
            RecordedVersion::Current {
                recorded: config::LISA_VERSION.to_string()
            }
        );
    }

    /// The same comparison as
    /// `config::tests::a_0_4_4_project_is_stale_against_the_0_5_0_release_candidate`,
    /// read the way an operator's project actually presents it: a recorded
    /// version in `.lisa.toml`. This is the reading every upgrade command
    /// branches on, so it is asserted through `inventory` and not only through
    /// the pure function underneath it.
    #[test]
    fn a_lisa_toml_written_by_0_4_4_reads_as_behind_this_binary() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join(".lisa.toml"), "version = \"0.4.4\"\n").unwrap();

        let currency = inventory(dir.path());
        assert_eq!(
            currency.recorded_version,
            RecordedVersion::Behind {
                recorded: "0.4.4".to_string()
            },
            "0.4.4 must read as behind {}",
            config::LISA_VERSION
        );

        let finding = find(&currency, ".lisa.toml").expect("a behind version is reported");
        assert_eq!(finding.kind, CurrencyKind::Behind);
        assert_eq!(finding.remedy, Remedy::Init);
    }

    #[test]
    fn a_lisa_toml_written_by_this_binary_reads_as_current() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join(".lisa.toml"), config::default_config_toml()).unwrap();

        let currency = inventory(dir.path());
        assert_eq!(
            currency.recorded_version,
            RecordedVersion::Current {
                recorded: config::LISA_VERSION.to_string()
            }
        );
        assert!(
            find(&currency, ".lisa.toml").is_none(),
            "the config this binary writes cannot already be behind it"
        );
    }

    #[test]
    fn a_directory_with_no_lisa_toml_has_nothing_to_be_current_with() {
        let dir = tempfile::tempdir().unwrap();
        let currency = inventory(dir.path());
        assert_eq!(currency.recorded_version, RecordedVersion::NoProject);
        assert!(currency.is_current());
    }

    #[test]
    fn frontmatter_reads_the_written_word_not_the_parsed_phase() {
        assert_eq!(
            frontmatter_value("---\nid: T-1\nphase: structure\n---\n\nBody\n", "phase").as_deref(),
            Some("structure")
        );
        assert_eq!(
            frontmatter_value("---\nphase: \"plan\"\n---\n", "phase").as_deref(),
            Some("plan")
        );
        // A `phase:` in the body is not frontmatter.
        assert_eq!(
            frontmatter_value("---\nid: T-1\n---\n\nphase: structure\n", "phase"),
            None
        );
        assert_eq!(frontmatter_value("no frontmatter here\n", "phase"), None);
    }
}
